displayName=Golems Don't Die
author=varzeki
support=https://github.com/Varzeki/golems-dont-die/issues
description=Golems should live forever.
tags=golem,crafting,wyrmscraig,skilling,cosmetic,npc,sailing,exploration,shortcuts,personality,hats
plugins=com.golemsdontdie.GolemsDontDiePlugin
version=3.1.0
build=standard
