displayName=Golems Don't Die
author=varzeki
support=https://github.com/Varzeki/golems-dont-die/issues
description=Golems should live forever.
tags=golem,crafting,wyrmscraig,skilling,cosmetic,npc,sailing,exploration,shortcuts
plugins=com.golemsdontdie.GolemsDontDiePlugin
version=2.0.2
build=standard
