displayName=Golems Don't Die
author=varzeki
support=https://github.com/Varzeki/golems-dont-die/issues
description=Makes Golems live and wander around forever instead of dying
tags=golem,crafting,wyrmscraig,skilling,cosmetic,npc
plugins=com.golemsdontdie.GolemsDontDiePlugin
version=1.0
build=standard
